package com.relief.domain.geofencing;

/**
 * Types of alerts that can be generated by geofences
 */
public enum GeofenceAlertType {
    BOUNDARY_VIOLATION,     // Violation of geofence boundary rules
    CAPACITY_EXCEEDED,      // Capacity limits exceeded
    RESOURCE_DEPLETION,     // Resources depleted below threshold
    EMERGENCY_DETECTED,     // Emergency situation detected
    UNAUTHORIZED_ACCESS,    // Unauthorized access attempt
    MAINTENANCE_REQUIRED,   // Maintenance required
    STATUS_CHANGE,          // Status change detected
    THRESHOLD_EXCEEDED,     // Monitoring threshold exceeded
    TIME_BASED_ALERT,       // Time-based alert triggered
    CUSTOM                  // Custom alert type
}



